Update sonatype-scan.yml

diff --git a/.github/workflows/sonatype-scan.yml b/.github/workflows/sonatype-scan.yml
--- a/.github/workflows/sonatype-scan.yml
+++ b/.github/workflows/sonatype-scan.yml
@@ -1,53 +1,48 @@
 name: Sonatype Workflow
+
 on: push
+
 jobs:
   sonatype-cli:
     runs-on: ubuntu-latest
     steps:
-      # Check out your code
       - name: Checkout
-        id: checkout
         uses: actions/checkout@v4
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+      - name: Build WAR
+        run: mvn package -DskipTests
 
-      - name: Build Docker image
-        run: docker build -t struts-container:1.0.0 .
-        
-      # Perform an evaluation 
       - name: Run evaluate action
         id: evaluate
         uses: sonatype/actions/evaluate@v1
         with:
-          iq-server-url: https://iq.ajoanes.ngrok.io/
+          iq-server-url: ${{ secrets.IQ_SERVER_URL }}
           username: ${{ secrets.IQ_USER }}
           password: ${{ secrets.IQ_PASSWORD }}
-          application-id: struts2-rce-demo__ajoanes98
-          scan-targets: struts2-rest-showcase.war container:struts-container:1.0.0
-          # upload-sarif-file: true
+          application-id: ${{ secrets.IQ_APPLICATION_ID }}
+          scan-targets: ${{ secrets.IQ_SCAN_TARGETS }}
         
-      # Fetch the SBOM file associated with the evaluation
-      - name: Fetch SBOM
-        uses: sonatype/actions/fetch-sbom@v1
-        if: ( success() || failure() ) && steps.evaluate.outputs.scan-id 
-        with:
-          iq-server-url: https://iq.ajoanes.ngrok.io/
-          username: ${{ secrets.IQ_USER }}
-          password: ${{ secrets.IQ_PASSWORD }}
-          application-id: struts2-rce-demo__ajoanes98
-          scan-id: ${{ steps.evaluate.outputs.scan-id }}
-          sbom-standard: cyclonedx
-          sbom-version: 1.5
-          sbom-format: json
-          artifact-name: struts-sbom
+      ## Fetch the SBOM file associated with the evaluation
+      #- name: Fetch SBOM
+      #  uses: sonatype/actions/fetch-sbom@v1
+      #  if: ( success() || failure() ) && steps.evaluate.outputs.scan-id 
+      #  with:
+      #    iq-server-url: https://iq.ajoanes.ngrok.io/
+      #    username: ${{ secrets.IQ_USER }}
+      #    password: ${{ secrets.IQ_PASSWORD }}
+      #    application-id: struts2-rce-demo__ajoanes98
+      #    scan-id: ${{ steps.evaluate.outputs.scan-id }}
+      #    sbom-standard: cyclonedx
+      #    sbom-version: 1.5
+      #    sbom-format: json
+      #    artifact-name: struts-sbom
 
-      - name: POST SBOM to SBOM Manager
-        if: always()
-        run: |
-          curl -i -u ${{ secrets.IQ_USER }}:${{ secrets.IQ_PASSWORD }} \
-            -H "X-CSRF-TOKEN: c9c664e5-697e-4415-bd40-34832c50d25d" \
-            -F file="struts-sbom" \
-            -F applicationId=aa94847f8b40474a044028f8039ec53 \
-            -F applicationVersion="1.0.0" \
-            -X POST "https://iq.ajoanes.ngrok.io/platform/api/v2/sbom/import"
+      #- name: POST SBOM to SBOM Manager
+      #  if: always()
+      #  run: |
+      #    curl -i -u ${{ secrets.IQ_USER }}:${{ secrets.IQ_PASSWORD }} \
+      #      -H "X-CSRF-TOKEN: c9c664e5-697e-4415-bd40-34832c50d25d" \
+      #      -F file="struts-sbom" \
+      #      -F applicationId=aa94847f8b40474a044028f8039ec53 \
+      #      -F applicationVersion="1.0.0" \
+      #      -X POST "https://iq.ajoanes.ngrok.io/platform/api/v2/sbom/import"
